//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int CId { get; set; }
        public string CName { get; set; }
        public double CFee { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Technology { get; set; }
    
        public virtual Status Status1 { get; set; }
        public virtual Technology Technology1 { get; set; }
    }
}
